### ISSUE TITLE
Can only mount shared folder once

### ISSUE THREAD

**Issue by ghost** [jwrdegoede/vboxsf#1]
Some issues with th install as follows:

xindi$ sudo make modules_install
[sudo] password for ian: 
make -C /lib/modules/`uname -r`/build M=`pwd` modules_install
make[1]: Entering directory '/usr/src/kernels/4.16.16-300.fc28.x86_64'
  INSTALL /home/ian/src/vboxsf/vboxsf.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: crypto/bio/bss_file.c:74
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: crypto/bio/bss_file.c:81
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  4.16.16-300.fc28.x86_64
make[1]: Leaving directory '/usr/src/kernels/4.16.16-300.fc28.x86_64'

Despite this I was able to mount a shared folder and it seemed to work (limited testing however).

After a reboot of the guest, I cannot mount the folder anymore, gives this error:

mount: /home/ian/mnt: mount(2) system call failed: File exists.

This issue exists on several VMs I've tried.  Host is Windows 7, guest Fedora 28 running 4.16.16-300.fc28.x86_64.

**Comment by jwrdegoede** [comment]
Hi,

What is the output of "lsmod" after the reboot?

And how are you trying to mount the shared folder,
which command are you executing?

REgards,

Hans

**Comment by ghost** [comment]
I cloned a fresh VM from my development master VM to do this.  Downloaded sources and compiled and installed, then did the depmod -a all as before.

After the reboot:

xindi$ lsmod | grep vbox
vboxsf                 32768  1
vboxguest              40960  6 vboxsf
vboxvideo              45056  2
drm_kms_helper        200704  1 vboxvideo
ttm                   126976  1 vboxvideo
drm                   454656  5 vboxvideo,ttm,drm_kms_helper
xindi$ sudo ./vbox.sh
[sudo] password for ian: 
mount: /home/ian/mnt: mount(2) system call failed: File exists.

The mount script vbox.sh (been using it for a long time) is:

#!/bin/bash
SHARENAME="Development"
MOUNTPOINT="/home/ian/mnt"
if [ ! -d "$MOUNTPOINT" ]; then
	mkdir "$MOUNTPOINT"
fi

mount -t vboxsf -o rw,uid=1000,gid=1000 $SHARENAME $MOUNTPOINT

This time I did not attempt to mount before rebooting, and after the reboot the error happened.  The odd thing is before the reboot vboxsf doesn't show up in the lsmod, but the mount seems to work (although this time I didn't try doing that).  In any case the factor seems to be the reboot, not that it works once and never again.

On another VM I built and installed the complete VirtualBox guest drivers from the guest editions virtual CD and it appears to actually work, including after rebooting the VM.  This requires saying yes to the scary option of toasting the resident drivers.  But it does work (FYI running VirtualBox 5.2.12).

**Comment by ghost** [comment]
OK I have found the cause of the problem and a workaround.  In the settings for the VM, in the shared folders tab, for the shared folder "C:\Development" I had it tagged as Auto-Mount.  I have always done this even though in practice (at least in Xfce) it never actually works.  With the drivers on the virtual CD this has never so far caused problems.  However with your vboxsf driver, when in a non-working state, if I look at the /etc/mtab file:

xindi$ cat /etc/mtab | grep vbox
Development /media/sf_Development vboxsf rw,nodev,relatime 0 0
xindi$ 

it shows the shared folder mounted (presumably through the Auto-Mount request)... but this mount doesn't actually work, the share point shows no files or folders, and it blocks (understandably) doing a manual mount.  

The fix for your driver is to un-check the Auto-Mount checkbox (since it doesn't work anyway) and do the manual mount, which works.  With Auto-Mount un-checked, after a reboot, and before attempting a mount, nothing is in the /etc/mtab file relating to vboxsf.

This fixes the issue for me, but it highlights a difference in behavior between your vboxsf driver and the one currently shipping with VirtualBox 5.2.12.

**Comment by ghost** [comment]
OK on another VM where I have the drivers installed from the VirtualBox cd, AND I have the Auto-Mount checked (even though it doesn't work) , this is what I get after I boot and login:

adric$ cat /etc/mtab | grep vboxsf
Development /media/sf_Development vboxsf rw,nodev,relatime 0 0

Then I do a manual mount:

adric$ sudo ./vbox.sh
[sudo] password for ian: 
adric$ cat /etc/mtab | grep vboxsf
Development /media/sf_Development vboxsf rw,nodev,relatime 0 0
Development /home/ian/mnt vboxsf rw,nodev,relatime 0 0

Apparently with the drivers VirtualBox supply on the cd it is able to add the working manual mount despite there being an existing one.

**Comment by jwrdegoede** [comment]
Thank you for the bug report, I'm about to push a new commit which fixes not being able to mount the same shared-folder twice.
