### ISSUE TITLE
warning: array subscript is above array bounds

### ISSUE THREAD

**Issue by fodrice** [jwrdegoede/vboxsf#6]
Got this building latest master.
/extdirs/sources/vboxsf-master_10.04.19/work/super.c:213:23: warning: array subscript is above array bounds [-Warray-bounds]
  root_path.string.utf8[1] = 0;

gcc-7.3.0
linux-4.19.32

**Comment by fodrice** [comment]
I haven't found memory allocation for root_path.string.utf8. Is that static array ?

**Comment by jwrdegoede** [comment]
On 10-04-19 18:12, Fodrice wrote:
> Got this building latest master.
> /extdirs/sources/vboxsf-master_10.04.19/work/super.c:213:23: warning: array subscript is above array bounds [-Warray-bounds]
> root_path.string.utf8[1] = 0;

The utf8 array is in a union with a utf16 array, so there is enough
space for this and the warning can be ignored.

I will try to actually fix the warning later.
