### ISSUE TITLE
Fedora32 beta & Rawhide compile issues

### ISSUE THREAD

**Issue by nixuser58** [jwrdegoede/vboxsf#7]
Hello,

Rawhide has some issues compiling the vboxsf driver and the Fedora 32 beta branch is the same as follows:

fc32beta$ make
make -C /lib/modules/`uname -r`/build M=`pwd` modules
make[1]: Entering directory '/usr/src/kernels/5.6.0-0.rc2.git0.1.fc32.x86_64'
  CC [M]  /home/admin/src/vboxsf/dir.o
  CC [M]  /home/admin/src/vboxsf/file.o
  CC [M]  /home/admin/src/vboxsf/utils.o
  CC [M]  /home/admin/src/vboxsf/vboxsf_wrappers.o
  CC [M]  /home/admin/src/vboxsf/super.o
/home/admin/src/vboxsf/super.c:57:21: error: variable ‘vboxsf_fs_parameters’ has initializer but incomplete type
   57 | static const struct fs_parameter_description vboxsf_fs_parameters = {
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/admin/src/vboxsf/super.c:58:3: error: ‘const struct fs_parameter_description’ has no member named ‘name’
   58 |  .name  = "vboxsf",
      |   ^~~~
/home/admin/src/vboxsf/super.c:58:11: warning: excess elements in struct initializer
   58 |  .name  = "vboxsf",
      |           ^~~~~~~~
/home/admin/src/vboxsf/super.c:58:11: note: (near initialization for ‘vboxsf_fs_parameters’)
/home/admin/src/vboxsf/super.c:59:3: error: ‘const struct fs_parameter_description’ has no member named ‘specs’
   59 |  .specs  = vboxsf_param_specs,
      |   ^~~~~
/home/admin/src/vboxsf/super.c:59:12: warning: excess elements in struct initializer
   59 |  .specs  = vboxsf_param_specs,
      |            ^~~~~~~~~~~~~~~~~~
/home/admin/src/vboxsf/super.c:59:12: note: (near initialization for ‘vboxsf_fs_parameters’)
/home/admin/src/vboxsf/super.c: In function ‘vboxsf_parse_param’:
/home/admin/src/vboxsf/super.c:70:21: error: passing argument 2 of ‘fs_parse’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   70 |  opt = fs_parse(fc, &vboxsf_fs_parameters, param, &result);
      |                     ^~~~~~~~~~~~~~~~~~~~~
      |                     |
      |                     const struct fs_parameter_description *
In file included from /home/admin/src/vboxsf/super.c:14:
./include/linux/fs_parser.h:69:39: note: expected ‘const struct fs_parameter_spec *’ but argument is of type ‘const struct fs_parameter_description *’
   69 |       const struct fs_parameter_spec *desc,
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/home/admin/src/vboxsf/super.c: At top level:
/home/admin/src/vboxsf/super.c:468:17: error: initialization of ‘const struct fs_parameter_spec *’ from incompatible pointer type ‘const struct fs_parameter_description *’ [-Werror=incompatible-pointer-types]
  468 |  .parameters  = &vboxsf_fs_parameters,
      |                 ^
/home/admin/src/vboxsf/super.c:468:17: note: (near initialization for ‘vboxsf_fs_type.parameters’)
/home/admin/src/vboxsf/super.c:57:46: error: storage size of ‘vboxsf_fs_parameters’ isn’t known
   57 | static const struct fs_parameter_description vboxsf_fs_parameters = {
      |                                              ^~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:268: /home/admin/src/vboxsf/super.o] Error 1
make[1]: *** [Makefile:1681: /home/admin/src/vboxsf] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.6.0-0.rc2.git0.1.fc32.x86_64'
make: *** [Makefile:10: all] Error 2
fc32beta$

**Comment by jwrdegoede** [comment]
The vboxsf module has been merged into the mainline kernel in 5.6-rc1, so there is no need to build it out of tree, just use the in tree version which is enabled by default in the Fedora 5.6 kernels.
